import React, { useState, useEffect } from 'react';
import NetworkAnalysis from './NetworkAnalysis';
import { CCTNSService } from '../services/cctnsService';
import { saveReport } from '../services/reportService';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const InvestigationDashboard = () => {
    const [dbStatus, setDbStatus] = useState('CONNECTING...');
    const [analytics, setAnalytics] = useState(null);
    const [searchQuery, setSearchQuery] = useState('');

    // Workflow States: 'IDLE' -> 'SEARCHING' -> 'MATCH_FOUND' -> 'ANALYZING' -> 'COMPLETE'
    const [workflowState, setWorkflowState] = useState('IDLE');

    const [searchResult, setSearchResult] = useState(null);
    const [graphData, setGraphData] = useState(null);
    const [aiBrief, setAiBrief] = useState(null);

    // Auto-Connect & Analytics Load
    useEffect(() => {
        const connectToCCTNS = async () => {
            try {
                await new Promise(r => setTimeout(r, 1000));
                await CCTNSService.initializeDatabase();
                const stats = CCTNSService.getAnalytics();
                setAnalytics(stats);
                setDbStatus('ONLINE');
            } catch (error) {
                console.error("Connection Failed", error);
                setDbStatus('ERROR');
            }
        };
        connectToCCTNS();
    }, []);

    const handleInitialSearch = () => {
        if (!searchQuery) return;
        setWorkflowState('SEARCHING');
        setSearchResult(null);
        setGraphData(null);
        setAiBrief(null);

        setTimeout(() => {
            const result = CCTNSService.search(searchQuery);
            if (result && result.matchFound) {
                setSearchResult(result);
                setWorkflowState('MATCH_FOUND');
            } else {
                setWorkflowState('IDLE');
                alert("No Record Found in CCTNS Database");
            }
        }, 800);
    };

    const runAIAnalysis = () => {
        setWorkflowState('ANALYZING');

        // Simulate Heavy AI Processing (Local Mode)
        // We set minimum 4.5s delay for the "Terminal Animation" to finish playing
        setTimeout(() => {
            if (searchResult) {
                const gData = CCTNSService.generateGraphData(searchResult);
                setGraphData(gData);

                // CALL LOCAL AI (Stable)
                const brief = CCTNSService.generateIntelligenceBrief(searchResult);
                setAiBrief(brief);

                // Auto-Save after AI finishes
                saveReport('Intel Search', searchQuery, searchResult.record);

                setWorkflowState('COMPLETE');
            }
        }, 4500); // 4.5 seconds for log animation
    };

    const downloadDossier = () => {
        if (!searchResult || !searchResult.matchFound) return;
        const rec = searchResult.record;
        const doc = new jsPDF();

        // Header
        doc.setFillColor(15, 23, 42);
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("CONFIDENTIAL CASE DOSSIER", 105, 20, { align: 'center' });
        doc.setFontSize(10);
        doc.text("GENERATED BY CCTNS INTELLIGENCE CORE", 105, 30, { align: 'center' });

        // Suspect Profile
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.text("SUSPECT IDENTITY", 15, 55);

        doc.autoTable({
            startY: 60,
            head: [['Field', 'Intelligence Data']],
            body: [
                ['Full Name', rec.Suspect_Name],
                ['Crime ID', rec.Crime_ID],
                ['Primary Mobile', rec.MSISDN],
                ['IMEI Device', rec.IMEI],
                ['IP Trace', rec.IP_Address],
                ['Reported Location', rec.Location],
                ['Risk Category', rec.Crime_Type.toUpperCase()],
                ['Confidence Score', '98% (HIGH)']
            ],
            theme: 'grid',
            headStyles: { fillColor: [220, 38, 38] }
        });

        // Linked Network
        const related = searchResult.relatedRecords || [];
        if (related.length > 0) {
            doc.text(`LINKED CRIMINAL NETWORK (${related.length} NODES)`, 15, doc.lastAutoTable.finalY + 15);

            const relatedData = related.map(r => [r.Crime_ID, r.Suspect_Name, r.Crime_Type, r.Location]);
            doc.autoTable({
                startY: doc.lastAutoTable.finalY + 20,
                head: [['ID', 'Name', 'Type', 'Location']],
                body: relatedData,
                theme: 'striped'
            });
        }

        doc.save(`CASE_${rec.Crime_ID}_${rec.Suspect_Name}.pdf`);
    };

    return (
        <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: '1rem', padding: '1rem', background: '#0f172a', color: 'white' }}>

            {/* TOP BAR: SEARCH & STATUS */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#1e293b', padding: '1rem', borderRadius: '12px', border: '1px solid #334155' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <div style={{ fontSize: '1.5rem' }}>🚔</div>
                    <div>
                        <h2 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 'bold' }}>CCTNS <span style={{ color: '#ef4444' }}>PRO</span></h2>
                        <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>NATIONAL INTELLIGENCE GRID</div>
                    </div>
                </div>

                <div style={{ display: 'flex', gap: '0.5rem', width: '500px' }}>
                    <input
                        type="text"
                        placeholder="ENTER SUSPECT DATA (Mobile, Name, IP)..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        onKeyPress={(e) => e.key === 'Enter' && handleInitialSearch()}
                        style={{ flex: 1, background: '#0f172a', border: '1px solid #475569', padding: '0.8rem', borderRadius: '8px', color: 'white', outline: 'none' }}
                    />
                    <button
                        onClick={handleInitialSearch}
                        className="hover-btn"
                        disabled={workflowState === 'SEARCHING' || workflowState === 'ANALYZING'}
                        style={{ background: '#ef4444', border: 'none', borderRadius: '8px', padding: '0 2rem', color: 'white', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s', opacity: (workflowState === 'SEARCHING' || workflowState === 'ANALYZING') ? 0.5 : 1 }}
                    >
                        {workflowState === 'SEARCHING' ? 'SCANNING...' : 'CHECK CCTNS'}
                    </button>
                    {workflowState === 'COMPLETE' && (
                        <button
                            onClick={downloadDossier}
                            style={{ background: '#3b82f6', border: 'none', borderRadius: '8px', padding: '0 1rem', color: 'white', cursor: 'pointer' }}
                            title="Download Official Case PDF"
                        >
                            ⬇ PDF
                        </button>
                    )}
                </div>

                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>SYSTEM STATUS</div>
                    <div style={{ color: dbStatus === 'ONLINE' ? '#10b981' : '#f59e0b', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '6px', justifyContent: 'flex-end' }}>
                        <span style={{ width: '8px', height: '8px', borderRadius: '50%', background: dbStatus === 'ONLINE' ? '#10b981' : '#f59e0b', boxShadow: '0 0 10px currentColor' }}></span>
                        {dbStatus}
                    </div>
                </div>
            </div>

            {/* MAIN CONTENT AREA */}
            <div style={{ flex: 1, display: 'grid', gridTemplateColumns: workflowState === 'COMPLETE' ? '350px 1fr' : '1fr', gap: '1rem', position: 'relative' }}>

                {/* 1. STATE: IDLE / ANALYTICS (NO SEARCH) */}
                {workflowState === 'IDLE' && (
                    <div className="analytics-dashboard" style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', alignContent: 'start' }}>

                        {/* Stat Cards */}
                        <div className="stat-card" style={{ background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <div style={{ color: '#94a3b8', fontSize: '0.8rem', marginBottom: '0.5rem' }}>TOTAL CASES INDEXED</div>
                            <div style={{ fontSize: '2.5rem', fontWeight: 'bold', color: '#fff' }}>{analytics?.totalCases || 0}</div>
                            <div style={{ fontSize: '0.7rem', color: '#10b981' }}>▲ Live Updating</div>
                        </div>
                        <div className="stat-card" style={{ background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <div style={{ color: '#94a3b8', fontSize: '0.8rem', marginBottom: '0.5rem' }}>ACTIVE HOTSPOTS</div>
                            <div style={{ fontSize: '2.5rem', fontWeight: 'bold', color: '#f59e0b' }}>{analytics?.hotspots?.length || 0}</div>
                            <div style={{ fontSize: '0.7rem', color: '#f59e0b' }}>High Alert Zones</div>
                        </div>
                        <div className="stat-card" style={{ background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <div style={{ color: '#94a3b8', fontSize: '0.8rem', marginBottom: '0.5rem' }}>NETWORK NODES</div>
                            <div style={{ fontSize: '2.5rem', fontWeight: 'bold', color: '#3b82f6' }}>{(analytics?.totalCases * 3.5).toFixed(0) || 0}</div>
                            <div style={{ fontSize: '0.7rem', color: '#3b82f6' }}>IPs, IMEIs, Phones</div>
                        </div>
                        <div className="stat-card" style={{ background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <div style={{ color: '#94a3b8', fontSize: '0.8rem', marginBottom: '0.5rem' }}>CLEARANCE RATE</div>
                            <div style={{ fontSize: '2.5rem', fontWeight: 'bold', color: '#10b981' }}>98.4%</div>
                            <div style={{ fontSize: '0.7rem', color: '#10b981' }}>AI Assisted</div>
                        </div>

                        {/* Charts / Lists */}
                        <div style={{ gridColumn: 'span 2', background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <h3 style={{ margin: '0 0 1rem 0', color: '#cbd5e1' }}>🔥 CRIME HOTSPOTS (Top 5)</h3>
                            {analytics?.hotspots?.map(([city, count], i) => (
                                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '0.8rem', borderBottom: '1px solid #334155', background: i === 0 ? '#451a1a' : 'transparent', borderRadius: i === 0 ? '6px' : '0' }}>
                                    <span style={{ color: i === 0 ? '#fca5a5' : '#cbd5e1', fontWeight: i === 0 ? 'bold' : 'normal' }}>{i + 1}. {city}</span>
                                    <span style={{ fontWeight: 'bold' }}>{count} Cases</span>
                                </div>
                            ))}
                        </div>

                        <div style={{ gridColumn: 'span 2', background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #334155' }}>
                            <h3 style={{ margin: '0 0 1rem 0', color: '#cbd5e1' }}>📊 TOP CRIME TRENDS</h3>
                            {analytics?.topCrimes?.map(([type, count], i) => (
                                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '1rem', padding: '0.5rem 0' }}>
                                    <div style={{ flex: 1, textAlign: 'right', fontSize: '0.8rem', color: '#94a3b8' }}>{type}</div>
                                    <div style={{ flex: 2, height: '8px', background: '#334155', borderRadius: '4px', overflow: 'hidden' }}>
                                        <div style={{ width: `${(count / analytics.topCrimes[0][1]) * 100}%`, height: '100%', background: i === 0 ? '#ef4444' : '#3b82f6' }}></div>
                                    </div>
                                    <div style={{ width: '40px', fontSize: '0.8rem', fontWeight: 'bold' }}>{count}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* 2. STATE: MATCH FOUND (CCTNS Success) */}
                {workflowState === 'MATCH_FOUND' && (
                    <div style={{ gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: '2rem' }}>
                        <div className="animate-slide-in" style={{ padding: '3rem', background: '#1e293b', borderRadius: '16px', border: '1px solid #fca5a5', textAlign: 'center', maxWidth: '600px', width: '100%', boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)' }}>
                            <div style={{ fontSize: '4rem', marginBottom: '1rem' }}>🚨</div>
                            <h2 style={{ fontSize: '2rem', color: '#ef4444', marginBottom: '0.5rem' }}>CRIMINAL RECORD FOUND</h2>
                            <p style={{ color: '#cbd5e1', fontSize: '1.2rem' }}>Target: <b>{searchResult.record.Suspect_Name}</b> linked to {searchResult.record.Crime_Type.toUpperCase()}</p>

                            <div style={{ margin: '2rem 0', padding: '1rem', background: '#0f172a', borderRadius: '8px', borderLeft: '4px solid #f59e0b', textAlign: 'left' }}>
                                <div style={{ fontWeight: 'bold', color: '#f59e0b', marginBottom: '5px' }}>CCTNS DATABASE ALERT:</div>
                                <div style={{ fontSize: '0.9rem', color: '#94a3b8' }}>
                                    Basic verification complete. Enhanced AI Analysis is recommended to trace hidden network connections, alias detection, and behavioral clustering using the offline dataset (1000 Records).
                                </div>
                            </div>

                            <button
                                onClick={runAIAnalysis}
                                className="hover-btn"
                                style={{ background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)', border: 'none', padding: '1rem 3rem', borderRadius: '50px', color: 'white', fontSize: '1.2rem', fontWeight: 'bold', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '10px', margin: '0 auto', boxShadow: '0 0 20px rgba(37, 99, 235, 0.5)' }}
                            >
                                <span>🤖</span> RUN AI NETWORK ANALYSIS
                            </button>
                        </div>
                    </div>
                )}

                {/* 3. STATE: ANALYZING (AI Processing Terminal) */}
                {workflowState === 'ANALYZING' && (
                    <div style={{ gridColumn: '1 / -1', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '2rem' }}>

                        <div style={{ width: '100%', maxWidth: '600px', background: '#09090b', borderRadius: '12px', border: '1px solid #334155', boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.5)', overflow: 'hidden', fontFamily: 'monospace' }}>
                            {/* Terminal Header */}
                            <div style={{ background: '#1e293b', padding: '0.5rem 1rem', display: 'flex', gap: '6px', borderBottom: '1px solid #334155' }}>
                                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#ef4444' }}></div>
                                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#f59e0b' }}></div>
                                <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: '#10b981' }}></div>
                                <span style={{ marginLeft: 'auto', fontSize: '0.7rem', color: '#94a3b8' }}>AI_CORE_PROCESSOR.exe</span>
                            </div>

                            {/* Terminal Body */}
                            <div style={{ padding: '1.5rem', height: '300px', overflowY: 'auto', color: '#22c55e', fontSize: '0.9rem', display: 'flex', flexDirection: 'column', gap: '5px' }}>
                                <LogLine text="> CCTNS Data Stream: CONNECTED" delay={0} />
                                <LogLine text="> Initializing Vector Space (1000 Dimensions)..." delay={500} />
                                <LogLine text="> Running Text Processing (NLP/TF-IDF)..." delay={1000} />
                                <LogLine text="> Generating 768-d Embeddings for Suspect Profile..." delay={1500} />
                                <LogLine text="> Executing KNN Algorithm (K=5) for Pattern Matching..." delay={2200} />
                                <LogLine text="> Calculating Euclidean Distances..." delay={2500} />
                                <LogLine text="> Graph Clustering: LOUVAIN ALGORITHM STARTED..." delay={3000} />
                                <LogLine text="> Sentiment Analysis: HOSTILE INTENT DETECTED" delay={3500} color="#f87171" />
                                <LogLine text="> AI Analysis Complete. Generating Intelligence Report..." delay={4200} />
                                <div className="typing-cursor" style={{ marginTop: '10px' }}>_</div>
                            </div>
                        </div>

                        <style>{`
                            .typing-cursor { display: inline-block; width: 8px; height: 15px; background: #22c55e; animation: blink 1s infinite; }
                            @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }
                            @keyframes fadeIn { from { opacity: 0; transform: translateY(5px); } to { opacity: 1; transform: translateY(0); } }
                        `}</style>
                    </div>
                )}

                {/* 4. STATE: COMPLETE (Show Graph) */}
                {workflowState === 'COMPLETE' && (
                    <>
                        {/* Left: Dossier Card */}
                        <div className="animate-slide-in" style={{ background: '#1e293b', padding: '1.5rem', borderRadius: '12px', border: '1px solid #475569', height: 'fit-content' }}>
                            <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
                                <div style={{ width: '80px', height: '80px', background: '#ef4444', borderRadius: '50%', display: 'grid', placeItems: 'center', margin: '0 auto 1rem', fontSize: '2.5rem', boxShadow: '0 0 20px rgba(239, 68, 68, 0.4)' }}>⚠️</div>
                                <h2 style={{ margin: 0, fontSize: '1.5rem' }}>{searchResult.record.Suspect_Name}</h2>
                                <div style={{ color: '#fca5a5', fontWeight: 'bold', marginTop: '0.2rem' }}>{searchResult.record.Crime_Type.toUpperCase()}</div>
                            </div>

                            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.8rem' }}>
                                <InfoRow label="CRIME ID" value={searchResult.record.Crime_ID} />
                                <InfoRow label="MOBILE" value={searchResult.record.MSISDN} />
                                <InfoRow label="LAST IP" value={searchResult.record.IP_Address} />
                                <InfoRow label="DEVICE IMEI" value={searchResult.record.IMEI} />
                                <InfoRow label="LOCATION" value={searchResult.record.Location} />
                            </div>

                            <div style={{ marginTop: '2rem', padding: '1rem', background: '#451a1a', borderRadius: '8px', border: '1px solid #ef4444' }}>
                                <div style={{ fontSize: '0.8rem', color: '#fca5a5', marginBottom: '5px' }}>INTELLIGENCE ALERT</div>
                                <div style={{ fontSize: '0.9rem' }}>Linked to <b>{searchResult.relatedRecords.length} other crimes</b> in the network graph. Immediate breakdown recommended.</div>
                            </div>

                            {/* AI BRIEF CARD */}
                            <div className="animate-slide-in" style={{ marginTop: '1rem', padding: '1rem', background: 'rgba(59, 130, 246, 0.1)', borderRadius: '8px', border: '1px solid #3b82f6' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
                                    <span style={{ fontSize: '1.2rem' }}>🤖</span>
                                    <div style={{ fontSize: '0.8rem', color: '#93c5fd', fontWeight: 'bold' }}>AI INTELLIGENCE BRIEF</div>
                                </div>
                                <div style={{ fontSize: '0.85rem', color: '#e0f2fe', lineHeight: '1.5', whiteSpace: 'pre-line' }}>
                                    {aiBrief || "Generating Analysis..."}
                                </div>
                            </div>
                        </div>

                        {/* Right: Network Graph */}
                        <div style={{ background: '#0f172a', border: '1px solid #334155', borderRadius: '12px', overflow: 'hidden', position: 'relative', minHeight: '600px' }}>
                            <div style={{ position: 'absolute', top: 10, left: 10, zIndex: 10, background: 'rgba(0,0,0,0.6)', padding: '5px 10px', borderRadius: '4px', fontSize: '0.8rem' }}>
                                🕸️ NEURAL LINK ANALYSIS ({graphData?.nodes?.length || 0} Nodes)
                            </div>
                            <NetworkAnalysis graphData={graphData} />
                        </div>
                    </>
                )}

            </div>

            <style>{`
                .hover-btn:hover { background: #dc2626 !important; transform: scale(1.02);box-shadow: 0 0 10px rgba(239,68,68,0.5); }
                .animate-slide-in { animation: slideIn 0.4s ease-out; }
                @keyframes slideIn { from { transform: translateX(-20px); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
            `}</style>
        </div >
    );
};

const InfoRow = ({ label, value }) => (
    <div style={{ display: 'flex', justifyContent: 'space-between', paddingBottom: '0.5rem', borderBottom: '1px solid #334155' }}>
        <span style={{ color: '#94a3b8', fontSize: '0.8rem' }}>{label}</span>
        <span style={{ fontWeight: 'bold', fontFamily: 'monospace' }}>{value}</span>
    </div>
);

const LogLine = ({ text, delay, color }) => {
    const [visible, setVisible] = useState(false);
    useEffect(() => {
        const timer = setTimeout(() => setVisible(true), delay);
        return () => clearTimeout(timer);
    }, [delay]);

    if (!visible) return null;
    return <div style={{ color: color || '#22c55e', animation: 'fadeIn 0.3s ease-out' }}>{text}</div>;
};

export default InvestigationDashboard;
